# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
selene = "Kampfkarren/selene@0.26.1"
lune = "filiptibell/lune@0.8.9"
darklua = "seaofvoices/darklua@0.14.0"
rojo = "rojo-rbx/rojo@7.4.1"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
blink = "1Axen/blink@0.15.4"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
